version: 2
updates:
  # Maintain dependencies for GitHub Actions, checking once a week
  # - package-ecosystem: "github-actions"
  #   directory: "/"
  #   schedule:
  #     interval: "weekly"

  # Maintain dependencies for multi-module project, checking every weekday
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
