name: CI Build
on:
  workflow_dispatch:
  push:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle to generate and submit dependency graphs
        uses: gradle/gradle-build-action@8baac4c8ef753599f92eeb509c246d09d6250fa6 # v3.3.0
        with:
          dependency-graph: generate-and-submit

      - name: Run the usual CI build (dependency-graph will be generated and submitted post-job)
        run: ./gradlew build

      - name: Check the github ref
        run: echo "Github ref ${{ github.ref }}"

      - name: Cache the JAR artifacts for a release if we are on the main branch.
        uses: actions/cache/save@v4
        if: github.ref == 'refs/heads/main'
        with:
          path: '**/build/libs/*.jar'
          key: jar-artifacts-${{ github.sha }}
