name: CI Build
on:
  workflow_dispatch:
  push:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle to generate and submit dependency graphs
        uses: gradle/gradle-build-action@982da8e78c05368c70dac0351bb82647a9e9a5d2 # v2.11.1
        with:
          dependency-graph: generate-and-submit

      - name: Run the usual CI build (dependency-graph will be generated and submitted post-job)
        run: ./gradlew build

      - name: Check the github ref
        run: echo "Github ref ${{ github.ref }}"

      - name: Cache the JAR artifacts for a release if we are on the main branch.
        uses: actions/cache/save@v4
        if: github.ref == 'refs/head/main'
        with:
          path: '**/build/libs/*.jar'
          # TODO: Add a commit ID to the cache key?
          key: jar-artifacts
