name: CI Release

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["CI Build"]
    types:
      - completed

jobs:
  release:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      actions: write
    # strategy:
    #   matrix:
    #     module: [application, library]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # TODO/TKTK: use dorny/paths-filter to see if certain paths changed - behavior of paths-ignore for a workflow.

      - name: Restore the Jar file cache
        id: cache-restore
        uses: actions/cache/restore@v4
        with:
          path: '**/build/libs/*.jar'
          key: jar-artifacts-${{ github.sha }}
          fail-on-cache-miss: true

      # NOTE: fail-on-cache-miss does not correctly fail the job. This is a workaround.
      # There is an open bug report for it here: https://github.com/actions/cache/issues/1265
      - name: Fail the job if there was a cache miss
        if: steps.cache-restore.outputs.cache-hit != 'true'
        run: echo "Unable to download cache data from previous job" && false

      - name: List out the build directories to check jar files
        run: find . -name *.jar -print

      - name: Delete the cache.
        run: gh cache delete jar-artifacts-${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
